### ISSUE TITLE
Exception in lobby

### ISSUE THREAD

**Issue by Fruktus** [Fruktus/QuadradiusPreservationProject#42]
Debug what causes the following exception:

```
[20:10:09.665] INFO Member joined lobby: MmM
Exception in thread Thread-28:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/qr/server/QRServer/common/clienthandler.py", line 69, in run
    message = RequestMessage.from_data(data)
  File "/qr/server/QRServer/common/messages.py", line 53, in from_data
    return _parse_data(data.decode('ascii'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)
Exception in thread Thread-34:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/qr/server/QRServer/common/clienthandler.py", line 69, in run
    message = RequestMessage.from_data(data)
  File "/qr/server/QRServer/common/messages.py", line 53, in from_data
    return _parse_data(data.decode('ascii'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb8 in position 0: ordinal not in range(128)
Exception in thread Thread-38:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/qr/server/QRServer/common/clienthandler.py", line 69, in run
    message = RequestMessage.from_data(data)
  File "/qr/server/QRServer/common/messages.py", line 53, in from_data
    return _parse_data(data.decode('ascii'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)
Exception in thread Thread-42:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/qr/server/QRServer/common/clienthandler.py", line 69, in run
    message = RequestMessage.from_data(data)
  File "/qr/server/QRServer/common/messages.py", line 53, in from_data
    return _parse_data(data.decode('ascii'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 2: ordinal not in range(128)
Exception in thread Thread-46:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/qr/server/QRServer/common/clienthandler.py", line 69, in run
    message = RequestMessage.from_data(data)
  File "/qr/server/QRServer/common/messages.py", line 53, in from_data
    return _parse_data(data.decode('ascii'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 1: ordinal not in range(128)
[21:51:05.756] INFO Member joined lobby: MmM
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/qr/server/QRServer/common/clienthandler.py", line 37, in _socket_reader
    data = self.cs.recv(2048)
TimeoutError: [Errno 110] Operation timed out
Exception in thread Thread-62:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/qr/server/QRServer/common/clienthandler.py", line 69, in run
    message = RequestMessage.from_data(data)
  File "/qr/server/QRServer/common/messages.py", line 53, in from_data
    return _parse_data(data.decode('ascii'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3: ordinal not in range(128)
Exception in thread Thread-64:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/qr/server/QRServer/common/clienthandler.py", line 69, in run
    message = RequestMessage.from_data(data)
  File "/qr/server/QRServer/common/messages.py", line 53, in from_data
    return _parse_data(data.decode('ascii'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 5: ordinal not in range(128)
[01:27:17.643] INFO Player left lobby: MmM
Exception in thread Thread-56:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/qr/server/QRServer/common/clienthandler.py", line 76, in run
    handler(message)
  File "/qr/server/QRServer/lobby/lobbyclient.py", line 135, in _handle_disconnect
    self.lobby_server.remove_client(self.player.idx)
  File "/qr/server/QRServer/lobby/lobbyserver.py", line 38, in remove_client
    self.broadcast_lobby_state(idx)
  File "/qr/server/QRServer/lobby/lobbyserver.py", line 68, in broadcast_lobby_state
    self.clients[i].send_msg(message)
  File "/qr/server/QRServer/common/clienthandler.py", line 94, in send_msg
    self.cs.send(message.to_data())
BrokenPipeError: [Errno 32] Broken pipe
Exception in thread Thread-70:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/qr/server/QRServer/common/clienthandler.py", line 76, in run
    handler(message)
  File "/qr/server/QRServer/lobby/lobbyclient.py", line 82, in _handle_join_lobby
    self.player.idx = self.lobby_server.add_client(self)
  File "/qr/server/QRServer/lobby/lobbyserver.py", line 30, in add_client
    self.broadcast_lobby_state(idx)
  File "/qr/server/QRServer/lobby/lobbyserver.py", line 68, in broadcast_lobby_state
    self.clients[i].send_msg(message)
  File "/qr/server/QRServer/common/clienthandler.py", line 94, in send_msg
    self.cs.send(message.to_data())
BrokenPipeError: [Errno 32] Broken pipe
Exception in thread Thread-72:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/qr/server/QRServer/common/clienthandler.py", line 76, in run
    handler(message)
  File "/qr/server/QRServer/lobby/lobbyclient.py", line 82, in _handle_join_lobby
    self.player.idx = self.lobby_server.add_client(self)
  File "/qr/server/QRServer/lobby/lobbyserver.py", line 30, in add_client
    self.broadcast_lobby_state(idx)
  File "/qr/server/QRServer/lobby/lobbyserver.py", line 68, in broadcast_lobby_state
    self.clients[i].send_msg(message)
  File "/qr/server/QRServer/common/clienthandler.py", line 94, in send_msg
    self.cs.send(message.to_data())
BrokenPipeError: [Errno 32] Broken pipe
Exception in thread Thread-74:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/qr/server/QRServer/common/clienthandler.py", line 76, in run
    handler(message)
  File "/qr/server/QRServer/lobby/lobbyclient.py", line 82, in _handle_join_lobby
    self.player.idx = self.lobby_server.add_client(self)
  File "/qr/server/QRServer/lobby/lobbyserver.py", line 30, in add_client
    self.broadcast_lobby_state(idx)
  File "/qr/server/QRServer/lobby/lobbyserver.py", line 68, in broadcast_lobby_state
    self.clients[i].send_msg(message)
  File "/qr/server/QRServer/common/clienthandler.py", line 94, in send_msg
    self.cs.send(message.to_data())
BrokenPipeError: [Errno 32] Broken pipe
Exception in thread Thread-78:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/qr/server/QRServer/common/clienthandler.py", line 76, in run
    handler(message)
  File "/qr/server/QRServer/lobby/lobbyclient.py", line 82, in _handle_join_lobby
    self.player.idx = self.lobby_server.add_client(self)
  File "/qr/server/QRServer/lobby/lobbyserver.py", line 30, in add_client
    self.broadcast_lobby_state(idx)
  File "/qr/server/QRServer/lobby/lobbyserver.py", line 68, in broadcast_lobby_state
    self.clients[i].send_msg(message)
  File "/qr/server/QRServer/common/clienthandler.py", line 94, in send_msg
    self.cs.send(message.to_data())
BrokenPipeError: [Errno 32] Broken pipe
Exception in thread Thread-80:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/qr/server/QRServer/common/clienthandler.py", line 76, in run
    handler(message)
  File "/qr/server/QRServer/lobby/lobbyclient.py", line 82, in _handle_join_lobby
    self.player.idx = self.lobby_server.add_client(self)
  File "/qr/server/QRServer/lobby/lobbyserver.py", line 30, in add_client
    self.broadcast_lobby_state(idx)
  File "/qr/server/QRServer/lobby/lobbyserver.py", line 68, in broadcast_lobby_state
    self.clients[i].send_msg(message)
  File "/qr/server/QRServer/common/clienthandler.py", line 94, in send_msg
    self.cs.send(message.to_data())
BrokenPipeError: [Errno 32] Broken pipe
Exception in thread Thread-82:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/qr/server/QRServer/common/clienthandler.py", line 76, in run
    handler(message)
  File "/qr/server/QRServer/lobby/lobbyclient.py", line 82, in _handle_join_lobby
    self.player.idx = self.lobby_server.add_client(self)
  File "/qr/server/QRServer/lobby/lobbyserver.py", line 30, in add_client
    self.broadcast_lobby_state(idx)
  File "/qr/server/QRServer/lobby/lobbyserver.py", line 68, in broadcast_lobby_state
    self.clients[i].send_msg(message)
  File "/qr/server/QRServer/common/clienthandler.py", line 94, in send_msg
    self.cs.send(message.to_data())
BrokenPipeError: [Errno 32] Broken pipe
Exception in thread Thread-84:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/qr/server/QRServer/common/clienthandler.py", line 76, in run
    handler(message)
  File "/qr/server/QRServer/lobby/lobbyclient.py", line 82, in _handle_join_lobby
    self.player.idx = self.lobby_server.add_client(self)
  File "/qr/server/QRServer/lobby/lobbyserver.py", line 30, in add_client
    self.broadcast_lobby_state(idx)
  File "/qr/server/QRServer/lobby/lobbyserver.py", line 68, in broadcast_lobby_state
    self.clients[i].send_msg(message)
  File "/qr/server/QRServer/common/clienthandler.py", line 94, in send_msg
    self.cs.send(message.to_data())
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by Fruktus** [comment]
As a side note - try and test the chat function, I suspect it may be related and it is something that we didn't do extensively.

**Comment by Fruktus** [comment]
https://github.com/Fruktus/QuadradiusPreservationProject/blob/master/QRServer/common/clienthandler.py#L69C1-L69C53
