### ISSUE TITLE
[BUG] Game - play again not working

### ISSUE THREAD

**Issue by Fruktus** [Fruktus/QuadradiusPreservationProject#58]
## **Platform**
- [x] Website player
- [ ] Launcher
- [ ] Server

## **Describe the bug**

Game exceptioned when trying to play again

## **Expected behavior**

Game starts again when playing again

## **Steps To Reproduce**

- start match
- resign
- play again

## **Screenshots**

```
[16:44:29.594] DEBUG Client connected from ('127.0.0.1', 42368)
[16:44:29.618] DEBUG Handling: HelloGameRequest(['<QR_G>'])
[16:44:29.619] DEBUG Handling: JoinGameRequest(['<L>', 'asdf', '21562', 'asd', '35617', 'd986ab224ab6ae3376707b153033d11e'])
Exception in thread Thread-46:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/QRServer/common/clienthandler.py", line 77, in run
    handler(message)
  File "/usr/local/lib/python3.9/site-packages/QRServer/game/gameclient.py", line 90, in _handle_join_game
    self.game_server.register_client(self)
  File "/usr/local/lib/python3.9/site-packages/QRServer/game/gameserver.py", line 22, in register_client
    self.matches[match_id].add_party(client_handler)
  File "/usr/local/lib/python3.9/site-packages/QRServer/common/classes.py", line 49, in add_party
    raise Exception('Too many parties for a match')
Exception: Too many parties for a match
[websockify game] 127.0.0.1 - - [17/Jan/2024 16:44:29] 127.0.0.1: Plain non-SSL (ws://) WebSocket connection
[websockify game] 127.0.0.1 - - [17/Jan/2024 16:44:29] connecting to: 127.0.0.1:3001
[16:44:29.708] DEBUG Client connected from ('127.0.0.1', 42372)
[16:44:29.732] DEBUG Handling: HelloGameRequest(['<QR_G>'])
[16:44:29.733] DEBUG Handling: JoinGameRequest(['<L>', 'asd', '35617', 'asdf', '21562', '7fa98aef1cd0e04066f08bbd97d5ad0d'])
Exception in thread Thread-48:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/QRServer/common/clienthandler.py", line 77, in run
    handler(message)
  File "/usr/local/lib/python3.9/site-packages/QRServer/game/gameclient.py", line 90, in _handle_join_game
    self.game_server.register_client(self)
  File "/usr/local/lib/python3.9/site-packages/QRServer/game/gameserver.py", line 22, in register_client
    self.matches[match_id].add_party(client_handler)
  File "/usr/local/lib/python3.9/site-packages/QRServer/common/classes.py", line 49, in add_party
    raise Exception('Too many parties for a match')
Exception: Too many parties for a match
```

**Comment by kjarosh** [comment]
Should be working now
