### ISSUE TITLE
[BUG] Exception in game when unknown unicode sent

### ISSUE THREAD

**Issue by Fruktus** [Fruktus/QuadradiusPreservationProject#65]
## **Platform**
- [ ] Website player
- [ ] Launcher
- [x] Server

```v1.1.0```

## **Describe the bug**

Another unhandled unicode exception, in game part

## **Expected behavior**

No crashes

## **Steps To Reproduce**

unknown, most likely unsupported char in chat

## **Screenshots**

```
[22:14:07.353] DEBUG Handling: GameChatMessage(['<S>', '<CHAT>', '����What are member matches?'])
[22:14:07.353] DEBUG Sending GameChatMessage(['<S>', '<CHAT>', '����What are member matches?']) to Fruktus
Exception in thread Thread-856:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/QRServer/common/clienthandler.py", line 77, in run
    handler(message)
  File "/usr/local/lib/python3.9/site-packages/QRServer/game/gameclient.py", line 102, in _handle_forward
    self.opponent_handler.send_msg(message)
  File "/usr/local/lib/python3.9/site-packages/QRServer/common/clienthandler.py", line 99, in send_msg
    self.cs.send(message.to_data())
  File "/usr/local/lib/python3.9/site-packages/QRServer/common/messages.py", line 21, in to_data
    return delim.join(self.args).encode('ascii') + b'\x00'
UnicodeEncodeError: 'ascii' codec can't encode characters in position 11-14: ordinal not in range(128)
```

**Comment by Fruktus** [comment]
Resolved in #61
